.TH "jsext" 1
.SH NAME
jsext \- JavaScript interpreter and libraries
.SH SYNOPSIS
.B jsext
[OPTION]... [FILE] [ARGUMENT]...
.SH DESCRIPTION
Evaluates FILE. If it is an anonymous JavaScript function, arguments are passed to it.
If no arguments are given, jsext opens an interactive session.
.SH OPTIONS
.TP
.B \-r, \-\-rcfile=RCFILE
Execute commands from RCFILE instead of the system wide
initialization file /usr/lib/jsext/0-init.js
.TP
.B \-e, \-\-eval=EXPR
Evaluate the expression
.TP
.B \-h, \-\-help
Print help
.SH "ENVIRONMENT"
.B JSEXT_FCGI
If this environment variable is defined, jsext will start as a fastCGI server.
.SH "AUTHOR"
Svein Berge
.SH "COPYRIGHT"
Copyright \(co 2006-2008 Berges Allmenndigitale Rådgivningstjeneste
.SH "REPORTING BUGS"
http://jsext.net/
.SH "SEE ALSO"
http://jsext.net/

