#!/bin/sh

# This script runs the jsext interpreter from the development source tree,
# avoiding pre-installed libraries.

cd `dirname $0`
dn=`pwd`
cd - > /dev/null
export LD_LIBRARY_PATH=$dn/js/src/Linux_All_OPT.OBJ/:$dn/libjsext
exec $dn/libjsext/jsext --rcfile $dn/global/0-init.js $*
