#!/bin/sh

# This script runs the jsext interpreter from the development source tree,
# avoiding pre-installed libraries.

cd `dirname $0`
dn=`pwd`
echo "run --rcfile global/0-init.js $*" > jsextdbg.cmd
cd global
export LD_LIBRARY_PATH=$dn/js/src/Linux_All_OPT.OBJ/:$dn/libjsext
gdb $dn/libjsext/jsext -x ../jsextdbg.cmd
