
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ctoxml_c_create_buffer
#define yy_delete_buffer ctoxml_c_delete_buffer
#define yy_flex_debug ctoxml_c_flex_debug
#define yy_init_buffer ctoxml_c_init_buffer
#define yy_flush_buffer ctoxml_c_flush_buffer
#define yy_load_buffer_state ctoxml_c_load_buffer_state
#define yy_switch_to_buffer ctoxml_c_switch_to_buffer
#define yyin ctoxml_cin
#define yyleng ctoxml_cleng
#define yylex ctoxml_clex
#define yylineno ctoxml_clineno
#define yyout ctoxml_cout
#define yyrestart ctoxml_crestart
#define yytext ctoxml_ctext
#define yywrap ctoxml_cwrap
#define yyalloc ctoxml_calloc
#define yyrealloc ctoxml_crealloc
#define yyfree ctoxml_cfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ctoxml_crestart(ctoxml_cin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ctoxml_cleng;

extern FILE *ctoxml_cin, *ctoxml_cout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ctoxml_ctext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ctoxml_ctext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ctoxml_crestart()), so that the user can continue scanning by
	 * just pointing ctoxml_cin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ctoxml_ctext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ctoxml_cleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ctoxml_cwrap()'s to do buffer switches
 * instead of setting up a fresh ctoxml_cin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ctoxml_crestart (FILE *input_file  );
void ctoxml_c_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ctoxml_c_create_buffer (FILE *file,int size  );
void ctoxml_c_delete_buffer (YY_BUFFER_STATE b  );
void ctoxml_c_flush_buffer (YY_BUFFER_STATE b  );
void ctoxml_cpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void ctoxml_cpop_buffer_state (void );

static void ctoxml_censure_buffer_stack (void );
static void ctoxml_c_load_buffer_state (void );
static void ctoxml_c_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ctoxml_c_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ctoxml_c_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ctoxml_c_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ctoxml_c_scan_bytes (yyconst char *bytes,int len  );

void *ctoxml_calloc (yy_size_t  );
void *ctoxml_crealloc (void *,yy_size_t  );
void ctoxml_cfree (void *  );

#define yy_new_buffer ctoxml_c_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ctoxml_censure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ctoxml_c_create_buffer(ctoxml_cin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ctoxml_censure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ctoxml_c_create_buffer(ctoxml_cin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *ctoxml_cin = (FILE *) 0, *ctoxml_cout = (FILE *) 0;

typedef int yy_state_type;

extern int ctoxml_clineno;

int ctoxml_clineno = 1;

extern char *ctoxml_ctext;
#define yytext_ptr ctoxml_ctext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ctoxml_ctext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ctoxml_cleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[310] =
    {   0,
        0,    0,  105,  103,  101,  101,   89,  103,  102,   95,
       88,  103,   83,   84,   93,   92,   80,   91,   87,   94,
       48,   48,   81,   77,   96,   82,   97,  100,   45,   45,
       85,   86,   98,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   78,
       99,   79,   90,   76,    0,   53,    0,  102,   62,   71,
       63,    0,    0,   60,   68,   58,   69,   59,   70,    0,
       51,    1,    2,   61,   52,   47,    0,   48,    0,   48,
       67,   73,   75,   74,   66,   45,    0,   64,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   10,   45,

       45,   45,   45,   45,   45,   18,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   65,   72,   49,
       55,    0,   51,    2,   51,    0,   52,   47,    0,   50,
       46,   57,   56,    0,   54,    0,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   16,   45,   19,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,   51,    0,   51,    0,   52,   50,
       46,   45,   45,   45,   45,   45,   44,   45,   45,    3,
       45,    5,    6,   45,   45,   45,   45,   12,   13,   45,

       45,   17,   20,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   34,   45,   45,    0,   51,   45,
       45,   45,   45,   45,   45,   44,   44,   44,   45,   45,
        4,    7,   45,   45,   45,   45,   15,   45,   45,   23,
       45,   45,   45,   45,   45,   45,   32,   45,   45,   41,
       45,   45,   45,   45,   45,   45,    0,   39,   45,   45,
       45,   11,   14,   45,   22,   24,   25,   26,   29,   30,
       45,   45,   45,   45,   38,   45,   45,   36,   45,    0,
       43,   27,   45,    9,   45,   31,   45,   45,   45,   45,
       28,   45,    8,   21,   33,   40,   45,   45,   37,   45,

       42,   45,   45,   45,   45,   45,   45,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   21,   20,   22,   20,   20,   20,   23,   24,   25,
       26,   27,   28,    1,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   32,   32,   35,   32,   32,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   32,   50,   51,   52,   53,
       54,   55,   32,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    5,    5,    5,    5,    1,    1,    1,    1,    5,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    6,    1,    6,    1
    } ;

static yyconst flex_int16_t yy_base[319] =
    {   0,
        0,    0,  563,  564,  564,  564,  536,   63,    0,  535,
       61,  523,  564,  564,  533,   57,  564,   58,   56,   68,
       84,  130,  564,  564,   54,  532,   62,  564,    0,  551,
      564,  564,  530,   50,  496,  498,   54,   53,   58,   59,
      499,   69,  498,  506,   75,  487,  496,  494,  499,  564,
       46,  564,  564,  564,   90,  564,  543,    0,  564,  564,
      564,  111,  122,  564,  564,  564,  564,  564,  564,  528,
      137,  564,    0,  564,  165,  200,  157,  121,    0,    0,
      518,  564,  564,  564,  517,    0,   91,  564,   96,  485,
      497,  487,  481,  493,  480,  495,  482,  488,  474,  475,

      472,  472,  475,  472,  469,    0,  468,  472,   83,  470,
       97,   75,  474,  467,   77,  141,  472,  564,  564,  564,
      564,  183,  564,    0,  193,  221,  564,  195,  187,  236,
      214,  564,  564,  156,  564,  517,  460,  474,  472,  463,
      457,  462,  468,  461,  457,  469,  464,  452,  108,  466,
      464,  460,  452,  458,  461,    0,  447,    0,  453,  450,
      439,  441,  443,  450,  436,  434,  434,  446,  436,  440,
      444,  446,  435,  241,  255,  275,  564,  259,  283,  564,
      259,  436,  439,  440,  143,  438,  334,  438,  431,    0,
      429,    0,    0,  411,  408,  391,  392,    0,    0,  378,

      375,    0,    0,  375,  375,  371,  383,  373,  377,  382,
      381,  379,  369,  374,    0,  362,  374,  300,  384,  367,
      373,  363,  364,  390,  368,    0,  167,  408,  358,  355,
        0,    0,  354,  350,  354,  284,    0,  275,  279,    0,
      287,  284,  285,  269,  278,  280,    0,  271,  274,    0,
      259,  264,  256,  259,  290,  268,  241,    0,  262,  241,
      241,    0,    0,  253,    0,    0,    0,    0,    0,    0,
      244,  240,  233,  234,    0,  217,  226,    0,  219,  201,
      564,    0,  221,    0,  208,    0,  209,  207,  197,  204,
        0,  185,    0,    0,    0,    0,  191,  184,    0,  165,

        0,  177,  160,  140,  125,   85,   34,    0,  564,  435,
      441,  447,  450,  455,   78,  461,  467,  472
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      309,    1,  309,  309,  309,  309,  309,  310,  311,  309,
      309,  312,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  313,  313,
      309,  309,  309,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  309,
      309,  309,  309,  309,  310,  309,  310,  311,  309,  309,
      309,  312,  312,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  314,  309,  309,  309,  309,  309,  315,   22,
      309,  309,  309,  309,  309,  313,  316,  309,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  309,  309,  309,
      309,  309,  309,  314,  309,  309,  309,  309,  309,  309,
      315,  309,  309,  316,  309,  316,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  309,  309,  309,  309,  309,  309,  309,
      309,  313,  313,  313,  313,  313,  309,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  309,  309,  313,
      313,  313,  313,  313,  313,  317,  317,  187,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  318,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  318,
      309,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_nxt[633] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   29,
       29,   29,   30,   29,   29,   31,    4,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   29,   42,   29,
       43,   29,   29,   29,   29,   44,   45,   46,   47,   48,
       49,   29,   29,   29,   50,   51,   52,   53,   56,   60,
       65,  118,   70,   67,   71,   71,   71,   71,   81,   82,
       72,  131,   66,   68,   69,   73,   61,   84,   85,   89,
       90,  308,   91,   74,   95,   56,  135,   98,   92,   57,

       75,   96,   76,   76,   76,   76,   99,   97,  100,  103,
      101,  119,  104,   77,  106,  165,   78,   78,   79,  102,
      120,  107,  110,  111,  309,  169,   57,  136,   77,  160,
      166,   62,  112,  170,   78,  113,   90,  137,  138,  139,
      161,  307,   78,  163,  140,   79,   75,   63,   80,   80,
       80,   80,  141,   78,   78,   71,   71,   71,   71,   77,
      164,  135,   78,   78,  194,  195,  122,  123,  227,  123,
      129,   78,  129,  306,   77,  130,  130,  130,  130,   78,
       78,  122,  123,  125,  125,  125,  125,  123,   78,  171,
      305,  172,  136,  223,  126,  127,  174,  127,  174,  304,

      224,  175,  175,  175,  175,  130,  130,  130,  130,  126,
      127,  125,  125,  125,  125,  127,   75,  303,   76,   76,
       76,   76,  176,  177,  302,  177,  301,  128,  128,   77,
      300,  257,  128,  128,  178,  299,  178,  176,  177,  179,
      179,  179,  179,  177,   77,  128,  181,  181,  298,  297,
      128,  296,  295,  128,  130,  130,  130,  130,  128,  175,
      175,  175,  175,  294,  181,  293,  180,  281,  180,  292,
      291,  290,  181,  175,  175,  175,  175,  179,  179,  179,
      179,  180,  289,  288,  287,  123,  180,  123,  218,  286,
      218,  181,  181,  219,  219,  219,  219,  285,  284,  283,

      123,  179,  179,  179,  179,  123,  282,  281,  279,  181,
      278,  277,  276,  127,  275,  127,  274,  181,  219,  219,
      219,  219,  273,  272,  271,  270,  269,  268,  127,  267,
      266,  265,  264,  127,  226,  227,  263,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  228,  228,  228,  228,  226,  226,  226,  226,
      226,  226,  228,  228,  228,  228,  228,  228,  228,  226,
      226,  226,  226,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  262,  226,

      261,  226,  219,  219,  219,  219,  260,  259,  258,  226,
      256,  255,  254,  253,  177,  252,  177,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  177,
      239,  238,  237,  236,  177,   55,   55,   55,   55,   55,
       55,   58,  235,   58,   58,   58,   58,   62,   62,  234,
       62,   62,   62,   86,   86,  124,  233,  124,  124,  124,
      124,  134,  134,  134,  134,  134,  134,  226,  232,  226,
      226,  226,  280,  280,  280,  280,  280,  280,  231,  230,
      229,  225,  222,  221,  220,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,

      202,  201,  200,  199,  198,  197,  196,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  309,
      173,  168,  167,  162,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  133,  132,  121,  309,  117,  116,  115,  114,
      109,  108,  105,   94,   93,   88,   87,   83,   64,   63,
       59,   54,  309,    3,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309
    } ;

static yyconst flex_int16_t yy_chk[633] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   11,
       16,   51,   19,   18,   19,   19,   19,   19,   25,   25,
       20,  315,   16,   18,   18,   20,   11,   27,   27,   34,
       34,  307,   34,   20,   37,   55,   87,   38,   34,    8,

       21,   37,   21,   21,   21,   21,   38,   37,   39,   40,
       39,   51,   40,   21,   42,  112,   21,   21,   21,   39,
       62,   42,   45,   45,   63,  115,   55,   87,   21,  109,
      112,   63,   45,  115,   21,   45,   89,   89,   89,   89,
      109,  306,   21,  111,   89,   21,   22,   62,   22,   22,
       22,   22,   89,   78,   78,   71,   71,   71,   71,   22,
      111,  134,   22,   22,  149,  149,   71,   71,  227,   71,
       77,   78,   77,  305,   22,   77,   77,   77,   77,   78,
       22,   71,   71,   75,   75,   75,   75,   71,   22,  116,
      304,  116,  134,  185,   75,   75,  122,   75,  122,  303,

      185,  122,  122,  122,  122,  129,  129,  129,  129,   75,
       75,  125,  125,  125,  125,   75,   76,  302,   76,   76,
       76,   76,  125,  125,  300,  125,  298,  128,  128,   76,
      297,  227,   76,   76,  126,  292,  126,  125,  125,  126,
      126,  126,  126,  125,   76,  128,  131,  131,  290,  289,
       76,  288,  287,  128,  130,  130,  130,  130,   76,  174,
      174,  174,  174,  285,  131,  283,  130,  280,  130,  279,
      277,  276,  131,  175,  175,  175,  175,  178,  178,  178,
      178,  130,  274,  273,  272,  175,  130,  175,  176,  271,
      176,  181,  181,  176,  176,  176,  176,  264,  261,  260,

      175,  179,  179,  179,  179,  175,  259,  257,  256,  181,
      255,  254,  253,  179,  252,  179,  251,  181,  218,  218,
      218,  218,  249,  248,  246,  245,  244,  243,  179,  242,
      241,  239,  238,  179,  187,  187,  236,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  235,  187,

      234,  187,  219,  219,  219,  219,  233,  230,  229,  228,
      225,  224,  223,  222,  219,  221,  219,  220,  217,  216,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  219,
      205,  204,  201,  200,  219,  310,  310,  310,  310,  310,
      310,  311,  197,  311,  311,  311,  311,  312,  312,  196,
      312,  312,  312,  313,  313,  314,  195,  314,  314,  314,
      314,  316,  316,  316,  316,  316,  316,  317,  194,  317,
      317,  317,  318,  318,  318,  318,  318,  318,  191,  189,
      188,  186,  184,  183,  182,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,

      157,  155,  154,  153,  152,  151,  150,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  139,  138,  137,  136,
      117,  114,  113,  110,  108,  107,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   85,   81,   70,   57,   49,   48,   47,   46,
       44,   43,   41,   36,   35,   33,   30,   26,   15,   12,
       10,    7,    3,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ctoxml_c_flex_debug;
int ctoxml_c_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ctoxml_ctext;
#line 1 "c_scan.l"
/*
* Copyright (c) 2006, Berges Allmenndigitale Rådgivningstjeneste
* All rights reserved.
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
*     * Redistributions of source code must retain the above copyright
*       notice, this list of conditions and the following disclaimer.
*     * Redistributions in binary form must reproduce the above copyright
*       notice, this list of conditions and the following disclaimer in the
*       documentation and/or other materials provided with the distribution.
*     * Neither the name of Berges Allmenndigitale Rådgivningstjeneste nor the
*       names of its contributors may be used to endorse or promote products
*       derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE BERGES AND CONTRIBUTORS ``AS IS'' AND ANY
* EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE BERGES AND CONTRIBUTORS BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#line 36 "c_scan.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "strbuf.h"
#include "c_gram.h"
#include "ctoxml.h"
static void count(void);
//extern int echo;
extern char *ctoxml_cterm;
extern char *ctoxml_cterm2;
extern int ctoxml_clineno;
extern char *ctoxml_filename;
static void preprocessor(void);
#line 760 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ctoxml_cwrap (void );
#else
extern int ctoxml_cwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( ctoxml_ctext, ctoxml_cleng, 1, ctoxml_cout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ctoxml_cin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ctoxml_cin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ctoxml_cin))==0 && ferror(ctoxml_cin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ctoxml_cin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ctoxml_clex (void);

#define YY_DECL int ctoxml_clex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ctoxml_ctext and ctoxml_cleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 51 "c_scan.l"

#line 915 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ctoxml_cin )
			ctoxml_cin = stdin;

		if ( ! ctoxml_cout )
			ctoxml_cout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ctoxml_censure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ctoxml_c_create_buffer(ctoxml_cin,YY_BUF_SIZE );
		}

		ctoxml_c_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ctoxml_ctext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 564 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "c_scan.l"
{ ctoxml_comment(0); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "c_scan.l"
{ count(); ctoxml_linecomment(0); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "c_scan.l"
{ count(); return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "c_scan.l"
{ count(); return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "c_scan.l"
{ count(); return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "c_scan.l"
{ count(); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "c_scan.l"
{ count(); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "c_scan.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "c_scan.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "c_scan.l"
{ count(); return(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "c_scan.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "c_scan.l"
{ count(); return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "c_scan.l"
{ count(); return(ENUM); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "c_scan.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "c_scan.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "c_scan.l"
{ count(); return(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "c_scan.l"
{ count(); return(GOTO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "c_scan.l"
{ count(); return(IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "c_scan.l"
{ count(); return(INT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "c_scan.l"
{ count(); return(LONG); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "c_scan.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "c_scan.l"
{ count(); return(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "c_scan.l"
{ count(); return(SHORT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "c_scan.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "c_scan.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "c_scan.l"
{ count(); return(STATIC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "c_scan.l"
{ count(); return(INLINE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "c_scan.l"
{ count(); return(INLINE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "c_scan.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "c_scan.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "c_scan.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "c_scan.l"
{ count(); return(UNION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "c_scan.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "c_scan.l"
{ count(); return(VOID); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "c_scan.l"
{ count(); return(VA); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "c_scan.l"
{ count(); return(INT64); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "c_scan.l"
{ count(); return(STDCALL); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "c_scan.l"
{ count(); return(CDECL); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "c_scan.l"
{ count(); return(CDECL); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "c_scan.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "c_scan.l"
{ count(); return(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "c_scan.l"
{ count(); return(DECLSPEC); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 94 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(ASM); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(ASM); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(check_type()); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 102 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 104 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 105 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 106 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(CONSTANT); }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 108 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext); return(STRING_LITERAL); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 109 "c_scan.l"
{ count(); ctoxml_cterm=strdup(ctoxml_ctext+1); return(STRING_LITERAL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "c_scan.l"
{ count(); return(ELIPSIS); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 112 "c_scan.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "c_scan.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "c_scan.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 115 "c_scan.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 116 "c_scan.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "c_scan.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 118 "c_scan.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "c_scan.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "c_scan.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 121 "c_scan.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 122 "c_scan.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 123 "c_scan.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 124 "c_scan.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 125 "c_scan.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 126 "c_scan.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 127 "c_scan.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 "c_scan.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 129 "c_scan.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 130 "c_scan.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 131 "c_scan.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 132 "c_scan.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 133 "c_scan.l"
{ count(); return(';'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 134 "c_scan.l"
{ count(); return('{'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 135 "c_scan.l"
{ count(); return('}'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 136 "c_scan.l"
{ count(); return(','); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 137 "c_scan.l"
{ count(); return(':'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 138 "c_scan.l"
{ count(); return('='); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 139 "c_scan.l"
{ count(); return('('); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 140 "c_scan.l"
{ count(); return(')'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 141 "c_scan.l"
{ count(); return('['); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 142 "c_scan.l"
{ count(); return(']'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 143 "c_scan.l"
{ count(); return('.'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 144 "c_scan.l"
{ count(); return('&'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 145 "c_scan.l"
{ count(); return('!'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 146 "c_scan.l"
{ count(); return('~'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 147 "c_scan.l"
{ count(); return('-'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 148 "c_scan.l"
{ count(); return('+'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 149 "c_scan.l"
{ count(); return('*'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 150 "c_scan.l"
{ count(); return('/'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 151 "c_scan.l"
{ count(); return('%'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 152 "c_scan.l"
{ count(); return('<'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 153 "c_scan.l"
{ count(); return('>'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 154 "c_scan.l"
{ count(); return('^'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 155 "c_scan.l"
{ count(); return('|'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 156 "c_scan.l"
{ count(); return('?'); }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 158 "c_scan.l"
{ count(); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 160 "c_scan.l"
{ count(); preprocessor(); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 162 "c_scan.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 164 "c_scan.l"
ECHO;
	YY_BREAK
#line 1523 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ctoxml_cin at a new source and called
			 * ctoxml_clex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ctoxml_cin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ctoxml_cwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ctoxml_ctext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ctoxml_clex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ctoxml_crealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ctoxml_crestart(ctoxml_cin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ctoxml_crealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 309);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ctoxml_ctext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ctoxml_crestart(ctoxml_cin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ctoxml_cwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ctoxml_ctext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ctoxml_crestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ctoxml_censure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ctoxml_c_create_buffer(ctoxml_cin,YY_BUF_SIZE );
	}

	ctoxml_c_init_buffer(YY_CURRENT_BUFFER,input_file );
	ctoxml_c_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ctoxml_c_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ctoxml_cpop_buffer_state();
	 *		ctoxml_cpush_buffer_state(new_buffer);
     */
	ctoxml_censure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ctoxml_c_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ctoxml_cwrap()) processing, but the only time this flag
	 * is looked at is after ctoxml_cwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ctoxml_c_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ctoxml_cin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ctoxml_c_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ctoxml_calloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ctoxml_c_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ctoxml_calloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ctoxml_c_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ctoxml_c_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ctoxml_c_create_buffer()
 * 
 */
    void ctoxml_c_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ctoxml_cfree((void *) b->yy_ch_buf  );

	ctoxml_cfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ctoxml_crestart() or at EOF.
 */
    static void ctoxml_c_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ctoxml_c_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ctoxml_c_init_buffer was _probably_
     * called from ctoxml_crestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ctoxml_c_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ctoxml_c_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ctoxml_cpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ctoxml_censure_buffer_stack();

	/* This block is copied from ctoxml_c_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ctoxml_c_switch_to_buffer. */
	ctoxml_c_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ctoxml_cpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ctoxml_c_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ctoxml_c_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ctoxml_censure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ctoxml_calloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ctoxml_censure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ctoxml_crealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ctoxml_censure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ctoxml_c_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ctoxml_calloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ctoxml_c_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ctoxml_c_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ctoxml_clex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ctoxml_c_scan_bytes() instead.
 */
YY_BUFFER_STATE ctoxml_c_scan_string (yyconst char * yystr )
{
    
	return ctoxml_c_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ctoxml_clex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ctoxml_c_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ctoxml_calloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ctoxml_c_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ctoxml_c_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ctoxml_c_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ctoxml_ctext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ctoxml_ctext[ctoxml_cleng] = (yy_hold_char); \
		(yy_c_buf_p) = ctoxml_ctext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ctoxml_cleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ctoxml_cget_lineno  (void)
{
        
    return ctoxml_clineno;
}

/** Get the input stream.
 * 
 */
FILE *ctoxml_cget_in  (void)
{
        return ctoxml_cin;
}

/** Get the output stream.
 * 
 */
FILE *ctoxml_cget_out  (void)
{
        return ctoxml_cout;
}

/** Get the length of the current token.
 * 
 */
int ctoxml_cget_leng  (void)
{
        return ctoxml_cleng;
}

/** Get the current token.
 * 
 */

char *ctoxml_cget_text  (void)
{
        return ctoxml_ctext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ctoxml_cset_lineno (int  line_number )
{
    
    ctoxml_clineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ctoxml_c_switch_to_buffer
 */
void ctoxml_cset_in (FILE *  in_str )
{
        ctoxml_cin = in_str ;
}

void ctoxml_cset_out (FILE *  out_str )
{
        ctoxml_cout = out_str ;
}

int ctoxml_cget_debug  (void)
{
        return ctoxml_c_flex_debug;
}

void ctoxml_cset_debug (int  bdebug )
{
        ctoxml_c_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ctoxml_clex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ctoxml_cin = stdin;
    ctoxml_cout = stdout;
#else
    ctoxml_cin = (FILE *) 0;
    ctoxml_cout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ctoxml_clex_init()
     */
    return 0;
}

/* ctoxml_clex_destroy is for both reentrant and non-reentrant scanners. */
int ctoxml_clex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ctoxml_c_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ctoxml_cpop_buffer_state();
	}

	/* Destroy the stack itself. */
	ctoxml_cfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ctoxml_clex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ctoxml_calloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ctoxml_crealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ctoxml_cfree (void * ptr )
{
	free( (char *) ptr );	/* see ctoxml_crealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "c_scan.l"



ctoxml_cwrap()
{
	return(1);
}

int ctoxml_ccolumn = 0;
int ctoxml_cfilepos = 0;

ctoxml_comment(char **at)
{
        static struct strbuf *dstr=0;
	struct Xml *commxml;
	int state=0;
	if (dstr==0) dstr=strbuf_new();

	if (!at) {
          ctoxml_ccolumn+=2;
          ctoxml_cfilepos+=2;
	}

	while(state!=2) {
	    char c;
	    if (at) c=*((*at)++);
	    else c=input();
	    if (c==0) {
	      if (at==0) break;
	      at=0;
	      c=input();
	      if (c==0) break;
	    }

	    strbuf_catchar(dstr,c);

	    if (!at) {
	      if (c == '\n') {
	        ctoxml_ccolumn = 0;
	        ctoxml_clineno ++;
	      } else if (c == '\t') {
	        ctoxml_ccolumn = ((ctoxml_ccolumn+7)/8)*8;
	      } else
	        ctoxml_ccolumn++;
	    }

	    switch(state) {
	    case 0:
	      if (c=='*') state=1;
	      break;
	    case 1:
	      if (c=='/') state=2;
	      else if (c!='*') state=0;
	      break;
	    }
	}
	if (state==2)
	  dstr->buf[dstr->len-2]=0;

	commxml=xml_text("comment","type",strdup("block"),NULL,
		    strdup(dstr->buf));
	xml_print(commxml);
	xml_free(commxml);

	strbuf_clear(dstr);
}

ctoxml_linecomment(char *comment)
{
	struct Xml *commxml;

	if (!comment) comment=ctoxml_ctext+2;
       
	commxml=xml_text("comment","type",strdup("line"),NULL,
		    strdup(comment));
	xml_print(commxml);
	xml_free(commxml);
}

void preprocessor(void) {
  char *directive;
  char *comment;

  comment=strstr(ctoxml_ctext, "/*");
  if (comment) {
    *comment=0;
    comment+=2;
    ctoxml_comment(&comment);
  } else
    comment=ctoxml_ctext;

  comment=strstr(comment, "//");
  if (comment) {
    *comment=0;
    comment+=2;
    ctoxml_linecomment(comment);
  }

  directive=ctoxml_ctext+1;
  directive+=strspn(directive," \t");

  if (strncmp(directive,"define",6)==0) {
    int spclen=strspn(directive+6," \t"); // Find start of identifier
    if (spclen && directive[6+spclen]) {
      char *startparen;
      char *endparen;
      char *macrovalue;
      struct Xml *ident_xml;
      struct Xml *def;
      char *macroname=strdup(directive+spclen+6); // Copy identifier and rest of define

      startparen=strchr(macroname,'(');
      if (startparen && strcspn(macroname," \t")>startparen-macroname) {
	  endparen=strchr(macroname,')');
          macrovalue=endparen+1;
	  macrovalue+=strspn(macrovalue," \t");
	  macrovalue=strdup(macrovalue);
	  *startparen=0; // Terminate identifier
      } else {
          char *identend=macroname+strcspn(macroname," \t"); // Find end of identifier
          startparen=0;
	  macrovalue=identend+strspn(identend," \t");
	  macrovalue=strdup(macrovalue);
          *identend=0; // Terminate identifier;
      }

      def=xml("define",NULL,
	      (ident_xml=xml_text("id",NULL,macroname)),
	      xml_text("v",NULL,macrovalue),NULL);

      if (startparen) {
        char *ident=startparen+1;
	if (ident>=endparen) {
	    xml_link(ident_xml,xml_text("pm",NULL,strdup("")));
	}
	while (ident<endparen) {
	    char *identend=ident+strcspn(ident," \t,)");
            *identend=0;
	    xml_link(ident_xml,xml_text("pm",NULL,strdup(ident)));
            ident=identend+1;
            ident+=strspn(ident," \t,");
        }
      }
     
      xml_print(def);
      xml_free(def);
//      stringhash_insert(ctoxml_defines, defname, defval);
    }
  } else if (strncmp(directive,"pragma",6)==0) {
    struct Xml *pragma;

    if (directive[6])
      ctoxml_cterm=strdup(directive+7);
    else
      ctoxml_cterm=strdup("");
    
    pragma = xml_text("pragma",NULL,ctoxml_cterm);
    xml_print(pragma);
    xml_free(pragma);

  } else if (atoi(ctoxml_ctext+1) || strncmp(directive, "line ",5)==0) {
    char *filenameend;
    char *tmpfilename=strchr(ctoxml_ctext, ' ');
    char *lineno;
    struct Xml *linexml;

    if (!(tmpfilename && tmpfilename[0])) return;
    ctoxml_clineno=atoi(tmpfilename+1);
    
    tmpfilename=strchr(tmpfilename+1, '\"');
    if (!(tmpfilename && tmpfilename[0])) return;
    
    tmpfilename++;

    ctoxml_filename=strdup(tmpfilename);
    filenameend=strchr(ctoxml_filename+1, '\"');
    if (filenameend) *filenameend=0;
    strncpy(ctoxml_filename_errmsg,ctoxml_filename,80);

    lineno=malloc(10);
    sprintf(lineno,"%d",ctoxml_clineno);
    linexml = xml("line","file",ctoxml_filename,"line",lineno,NULL,NULL);
    xml_print(linexml);
    xml_free(linexml);
    ctoxml_clineno--;
  }
}

void count(void)
{
  int i;
  for (i = 0; ctoxml_ctext[i] != '\0'; i++) {
    if (ctoxml_ctext[i] == '\n') {
      ctoxml_ccolumn = 0;
      ctoxml_clineno ++;
    } else if (ctoxml_ctext[i] == '\t') {
      ctoxml_ccolumn = ((ctoxml_ccolumn+7)/8)*8;
    } else
      ctoxml_ccolumn ++;
    ctoxml_cfilepos++;
  }
      //	if (echo) ECHO;
}

char *ctoxml_cterm=0;
char *ctoxml_filename=0;
char ctoxml_filename_errmsg[80];
char *ctoxml_cterm2=0;
int ctoxml_clineno;

int check_type()
{
	if (stringhash_search(ctoxml_typedefs,ctoxml_ctext)) {
		return(TYPE_NAME);
	}
	return(IDENTIFIER);
}

