Document: jsext
Title: Debian jsext Manual
Author: <insert document author here>
Abstract: This manual describes what jsext is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jsext/jsext.sgml.gz

Format: postscript
Files: /usr/share/doc/jsext/jsext.ps.gz

Format: text
Files: /usr/share/doc/jsext/jsext.text.gz

Format: HTML
Index: /usr/share/doc/jsext/html/index.html
Files: /usr/share/doc/jsext/html/*.html

  
